name: build_and_deploy_umg



on: 
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Steam AppID'     
        required: true
        default: '1234567'
      build_desc:
        description: 'Version description. eg: v0.0.0'  
        required: true
      release_branch: 
        description: 'Steam release branch'
        required: true
        default: 'prerelease'


jobs:
  deployToSteam:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}          

          appId: ${{ inputs.app_id }}
          # Todo ^^^ this might fail, since app_id is a string, and it expects number

          buildDescription: ${{ inputs.build_desc }}
          rootPath: build
          depot1Path: build/win64
          # depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
          depot2Path: build/linux64
          releaseBranch: ${{ inputs.release_branch }}
