
#
# Originally taken from 
# https://github.com/pfirsich/lovejam20/blob/349f645ec65db9563b1c58f176f0207051294875/.github/workflows/build.yml
#
#


name: build_umg


on: workflow_dispatch


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Preps
    - name: Install libfuse2
      run: sudo apt-get install libfuse2
    - name: Download AppImageTool
      run: |
        set -e
        curl -Lfo appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool
    # Checkout UMGClient and the mods
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        path: main
    - name: Checkout Mods
      uses: actions/checkout@v4
      with:
        repository: UntitledModGame/umg-mods
        ssh-key: ${{ secrets.UMG_MODS_CICD }}
        path: main/builtin_mods
    # Clone and build Darklua:
    - name: Clone Darklua
      uses: actions/checkout@v4
      with:
        repository: seaofvoices/darklua
        ref: v0.13.1
        path: darklua
    - name: Build Darklua
      working-directory: darklua
      run: cargo build --locked --release --target x86_64-unknown-linux-gnu
      env:
        CARGO_TARGET_DIR: output
    # Run darklua processor across lua files:
    - name: Darklua Preprocessing
      run: |
        set -e
        chmod +x darklua/output/x86_64-unknown-linux-gnu/release/darklua
        ./darklua/output/x86_64-unknown-linux-gnu/release/darklua process main main --config main/.darklua.json
    # Linux fusing
    - name: Extract LOVE AppImage (Linux Fusing)
      run: main/build/love/linux64/love.AppImage --appimage-extract
    - name: Copy UMG to /share/umg
      run: |
        set -e
        cp -r main squashfs-root/share/umg
    - name: Cleanup (Linux Fusing)
      working-directory: squashfs-root/share/umg
      run: |
        rm -rf .git ARCHITECTURE build *.toml *.dll config.ld r.bat steam_api64.lib
        rm -rf builtin_mods/.git
    - name: Update AppRun
      working-directory: squashfs-root
      run: |
        set -e
        sed 's@#FUSE_PATH="$APPDIR/my_game.love"@FUSE_PATH="$APPDIR/share/umg"@' AppRun > newAppRun
        mv newAppRun AppRun
        chmod +x AppRun
    - name: Add 3rd-party Libs (Linux Fusing)
      run: |
        set -e
        cp main/build/dlls/linux64/luasteam.so squashfs-root/share/lua/5.1/luasteam.so
        cp main/build/dlls/linux64/libsteam_api.so squashfs-root/lib/libsteam_api.so
    - name: Build AppImage (Linux Fusing)
      run: ./appimagetool squashfs-root umg.AppImage
    - name: Artifact Linux AppImage
      uses: actions/upload-artifact@v4
      with:
        name: umg-linux
        path: umg.AppImage
        if-no-files-found: error
