name: build_umg

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Steam App Type'     
        required: false
        type: choice
        options:
        - release
        - demo
        - playtest
      build_desc:
        description: 'Version description. eg: v0.0.0'  
        required: false
      release_branch: 
        description: 'Steam release branch'
        required: false
        default: 'prerelease'


jobs:
  prepare-resource:
    runs-on: windows-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Copy LOVE for Manifest
      shell: cmd
      run: copy build\love\win64\love.exe build\resources\love.exe
    - name: Generate Resource
      env:
        VERSION: ${{ (github.event_name == 'workflow_dispatch' && inputs.build_desc != '') && inputs.build_desc || '0.0.0' }}
      shell: cmd
      working-directory: build
      run: python generate_resource_data.py %VERSION% resources/umg_version.rc.in resources/umg_version.rc
    - name: Compile VersionInfo Resource
      shell: cmd
      working-directory: build/resources
      run: start /WAIT ResourceHacker.exe -open umg_version.rc -save umg_version.res -action compile
    - name: Replace love.exe Resources
      shell: cmd
      working-directory: build/resources
      run: start /WAIT ResourceHacker.exe -script resourcehackerscript.txt
    - name: Artifact Modified LOVE
      uses: actions/upload-artifact@v4
      with:
        name: manifested-love
        path: build/resources/love_manifested.exe
        if-no-files-found: error
  build:
    runs-on: ubuntu-latest
    needs: prepare-resource
    steps:
    # Preps
    - name: Install libfuse2
      run: sudo apt-get install libfuse2
    - name: Download AppImageTool
      run: |
        set -e
        curl -Lfo appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool
    # Checkout UMGClient and the mods
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        path: main
    - name: Checkout Mods
      uses: actions/checkout@v4
      with:
        repository: UntitledModGame/umg-mods
        ssh-key: ${{ secrets.UMG_MODS_CICD }}
        path: main/builtin_mods
    # Add LOOTPLOT_DEMO.txt if appropriate:
    - name: Add LOOTPLOT_DEMO.txt
      if: inputs.build_type == 'demo'
      run: touch main/LOOTPLOT_DEMO.txt
    # Clone and build Darklua:
    - name: Clone Darklua
      uses: actions/checkout@v4
      with:
        repository: seaofvoices/darklua
        ref: v0.13.1
        path: darklua
    - name: Get Darklua Commit
      id: darklua
      working-directory: darklua
      run: git log --pretty=format:'commit=%H' -1 > $GITHUB_OUTPUT
    - name: Cache Darklua
      id: darklua-cache
      uses: actions/cache@v4
      with:
        path: darklua/output
        key: darklua-${{ steps.darklua.outputs.commit }}
    - name: Build Darklua
      if: steps.darklua-cache.outputs.cache-hit != 'true'
      working-directory: darklua
      env:
        CARGO_TARGET_DIR: output
      run: cargo build --locked --release --target x86_64-unknown-linux-gnu
    # Run darklua processor across lua files:
    - name: Darklua Preprocessing
      run: |
        set -e
        chmod +x darklua/output/x86_64-unknown-linux-gnu/release/darklua
        ./darklua/output/x86_64-unknown-linux-gnu/release/darklua process main main --config main/.darklua.json
    # Linux fusing
    - name: Extract LOVE AppImage (Linux Fusing)
      run: main/build/love/linux64/love.AppImage --appimage-extract
    - name: Copy UMG For LOVE
      run: cp -r main umg_presetup
    - name: Remove Confidential Files (Linux Fusing)
      working-directory: umg_presetup
      run: |
        shopt -s globstar
        rm -rf .git .darklua.json ARCHITECTURE build *.toml *.dll config.ld r.bat steam_api64.lib .git*
        rm -rf builtin_mods/.git
        rm -rf **/*.md
    - name: Archive UMG to /share/umg.love
      working-directory: umg_presetup
      run: 7z a -tzip -mx9 ../squashfs-root/share/umg.love *
    - name: Update AppRun
      working-directory: squashfs-root
      run: |
        set -e
        sed 's@#FUSE_PATH="$APPDIR/my_game.love"@FUSE_PATH="$APPDIR/share/umg.love"@' AppRun > newAppRun
        mv newAppRun AppRun
        chmod +x AppRun
    - name: Add 3rd-party Libs (Linux Fusing)
      run: |
        set -e
        mkdir -p squashfs-root/lib/lua/5.1
        cp main/build/dlls/linux64/libsteam_api.so squashfs-root/lib/libsteam_api.so
        cp main/build/dlls/linux64/luasteam.so squashfs-root/lib/lua/5.1/luasteam.so
    - name: Build AppImage (Linux Fusing)
      run: ./appimagetool squashfs-root umg.AppImage
    - name: Artifact Linux AppImage
      uses: actions/upload-artifact@v4
      with:
        name: umg-linux
        path: umg.AppImage
        if-no-files-found: error
    # Windows fusing
    - name: Download Manifested LOVE
      uses: actions/download-artifact@v4
      with:
        name: manifested-love
        path: manifested-love
    - name: Prepare Windows Fusing
      run: |
        set -e
        cp -r main/build/love/win64 windows
        rm windows/love.exe windows/love.ico windows/lovec.exe
    - name: Add 3rd-party Libs (Windows Fusing)
      run: |
        set -e
        cp main/build/dlls/win64/luasteam.dll windows/luasteam.dll
        cp main/build/dlls/win64/steam_api.dll windows/steam_api.dll
        cp main/build/dlls/win64/steam_api64.dll windows/steam_api64.dll
        cp main/steam_appid.txt windows/steam_appid.txt
    - name: Fuse (Windows)
      run: cat manifested-love/love_manifested.exe squashfs-root/share/umg.love > windows/umg.exe
    - name: Artifact Windows Binaries
      uses: actions/upload-artifact@v4
      with:
        name: umg-windows
        path: windows
        if-no-files-found: error
  deploy:
    needs: build
    if: inputs.build_type != '' && inputs.build_desc != ''
    runs-on: ubuntu-latest
    steps:
      - name: Test Secrets Validity
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF}}
        shell: python
        run: |
          import os

          if not (os.environ["STEAM_USERNAME"] and os.environ["STEAM_CONFIG_VDF"]):
            raise Exception("Secrets are improperly set up!")
      - name: Output Steam AppID
        id: appid
        shell: python
        env:
          BUILD_TYPE: ${{ inputs.build_type }}
        run: |
          import os

          APPIDS = {"playtest": 3157410, "demo": 3614120, "release": 3057190}
          with open(os.environ["GITHUB_OUTPUT"], "w") as f:
              f.write(f"id={APPIDS[os.environ['BUILD_TYPE']]}")
      - name: Download Artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: umg-windows
          path: build/win64
      - name: Download Artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: umg-linux
          path: umg-linux
      - name: Extract AppImage for Steam
        working-directory: umg-linux
        run: |
          set -e
          chmod +x umg.AppImage
          ./umg.AppImage --appimage-extract
          mv squashfs-root ../build/linux64
      - name: Delete steam_appid.txt
        run: |
          rm build/win64/steam_appid.txt || true
      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3
        continue-on-error: false
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}

          appId: ${{ steps.appid.outputs.id }}
          # Todo ^^^ this might fail, since app_id is a string, and it expects number

          buildDescription: ${{ inputs.build_desc }}
          rootPath: build
          depot1Path: win64
          # depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
          depot2Path: linux64
          releaseBranch: ${{ inputs.release_branch }}
